### ISSUE TITLE
提供的权重文件跑出的结果不对

### ISSUE THREAD

**Issue by ISO497** [astro-ck/Road-Extraction#1]
您好，我用您之前提供给我的权重文件，运行test.py文件，得出的结果与预期相差很大。

我是用deepglobe比赛的数据集，图片大小为1024*1024，共有1101张图片。

道路提取的结果残缺很严重，且大部分的结果为空，没有提取的道路。

我想问一下是不是您提供的权重文件有误，或者是别的地方出了错？

期待您的回复，谢谢。
![部分结果缩略图](https://user-images.githubusercontent.com/68182991/95230541-a08f4e80-0834-11eb-991a-69c6e7bd3727.jpg)

**Comment by kai-zhang-er** [comment]
您好，在我们的论文里面，BSNet是用在boosting里面的，是为了修补提升第一个步骤提取出来的道路结果。具体使用的详情可以参考论文的method。我提供给你的模型是马萨诸塞州的，分辨率和deepglobe也不一样。我们近期会整理一下预训练模型，然后更新到本仓库中。谢谢你的关注。

**Comment by ISO497** [comment]
好的，谢谢

**Comment by kai-zhang-er** [comment]
已经提供了新的预训练模型与代码，可以参考readme。关于BSNet的模型建议自己训练，因为它与数据集有关。BSNet的代码我们还会继续整理，可以先用base-segmentation的方法。
